-- Back-fills the message template catalog for every tenant.
-- Rendering now throws when a (key, channel) has no active row, so these rows
-- are required for any outbound message to leave the system.
-- Generated by scripts/generate-template-migration.ts — do not edit by hand.

insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_availability', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, für die geförderte Weiterbildung brauchen wir noch eine kurze Rückmeldung zu Ihrer Verfügbarkeit (ca. 20 Stunden pro Woche über 6 Monate). Das dauert zwei Minuten:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_availability', 'email'::channel, 'de', 'Ihre Verfügbarkeit für die geförderte Weiterbildung', 'Hallo {{firstName}}, für die geförderte Weiterbildung brauchen wir noch eine kurze Rückmeldung zu Ihrer Verfügbarkeit (ca. 20 Stunden pro Woche über 6 Monate). Das dauert zwei Minuten:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_start_aptitude_test', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, Ihr Eignungstest ist freigeschaltet. Sie brauchen dafür rund 30 Minuten und können jederzeit starten:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_start_aptitude_test', 'email'::channel, 'de', 'Ihr Eignungstest ist bereit', 'Hallo {{firstName}}, Ihr Eignungstest ist freigeschaltet. Sie brauchen dafür rund 30 Minuten und können jederzeit starten:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_request_correct_contact', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, wir konnten Sie unter der hinterlegten Nummer nicht erreichen. Bitte prüfen und ergänzen Sie kurz Ihre Kontaktdaten, damit wir Sie zurückrufen können:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_request_correct_contact', 'email'::channel, 'de', 'Bitte prüfen Sie Ihre Kontaktdaten', 'Hallo {{firstName}}, wir konnten Sie unter der hinterlegten Nummer nicht erreichen. Bitte prüfen und ergänzen Sie kurz Ihre Kontaktdaten, damit wir Sie zurückrufen können:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_reachability', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, wir haben Sie leider nicht erreicht. Sagen Sie uns kurz, wann und unter welcher Nummer wir Sie am besten zurückrufen dürfen:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_reachability', 'email'::channel, 'de', 'Wann erreichen wir Sie am besten?', 'Hallo {{firstName}}, wir haben Sie leider nicht erreicht. Sagen Sie uns kurz, wann und unter welcher Nummer wir Sie am besten zurückrufen dürfen:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_reschedule_after_no_show', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, Ihr letzter Beratungstermin hat leider nicht geklappt. Wählen Sie hier einen neuen Termin, der Ihnen besser passt:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_reschedule_after_no_show', 'email'::channel, 'de', 'Neuen Termin für Ihre Beratung wählen', 'Hallo {{firstName}}, Ihr letzter Beratungstermin hat leider nicht geklappt. Wählen Sie hier einen neuen Termin, der Ihnen besser passt:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_give_consent', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, damit wir Ihren Förderantrag vorbereiten dürfen, benötigen wir Ihre Einwilligung zur Verarbeitung Ihrer Daten. Sie können sie hier erteilen:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_give_consent', 'email'::channel, 'de', 'Einwilligung für Ihren Förderantrag', 'Hallo {{firstName}}, damit wir Ihren Förderantrag vorbereiten dürfen, benötigen wir Ihre Einwilligung zur Verarbeitung Ihrer Daten. Sie können sie hier erteilen:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_upload_documents', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, für Ihren Förderantrag fehlen noch Unterlagen. Sie können sie hier direkt hochladen:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_upload_documents', 'email'::channel, 'de', 'Unterlagen für Ihren Förderantrag', 'Hallo {{firstName}}, für Ihren Förderantrag fehlen noch Unterlagen. Sie können sie hier direkt hochladen:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_sign_document', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, für Ihren Förderantrag liegt ein Dokument zur Unterschrift bereit: {{title}}. Sie können es hier prüfen und unterschreiben:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_sign_document', 'email'::channel, 'de', 'Dokument zur Unterschrift', 'Hallo {{firstName}}, für Ihren Förderantrag liegt ein Dokument zur Unterschrift bereit: {{title}}. Sie können es hier prüfen und unterschreiben:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_submission', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, bitte bestätigen Sie kurz, dass die Unterlagen bei der Agentur für Arbeit eingereicht wurden:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_submission', 'email'::channel, 'de', 'Bitte bestätigen Sie die Einreichung', 'Hallo {{firstName}}, bitte bestätigen Sie kurz, dass die Unterlagen bei der Agentur für Arbeit eingereicht wurden:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_provide_betriebsnummer', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, für den Förderantrag Ihrer Mitarbeiterin oder Ihres Mitarbeiters fehlt noch die Betriebsnummer Ihres Unternehmens. Sie können sie hier eintragen:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_provide_betriebsnummer', 'email'::channel, 'de', 'Betriebsnummer für den Förderantrag', 'Hallo {{firstName}}, für den Förderantrag Ihrer Mitarbeiterin oder Ihres Mitarbeiters fehlt noch die Betriebsnummer Ihres Unternehmens. Sie können sie hier eintragen:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_ags_status', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, für den Förderantrag benötigen wir noch Ihre Angabe zur Betriebsgröße (Zahl der Beschäftigten). Sie können sie hier ergänzen:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_ags_status', 'email'::channel, 'de', 'Angaben zur Betriebsgröße', 'Hallo {{firstName}}, für den Förderantrag benötigen wir noch Ihre Angabe zur Betriebsgröße (Zahl der Beschäftigten). Sie können sie hier ergänzen:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_time_model', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, bitte bestätigen Sie kurz das Arbeitszeitmodell und die Freistellung für die Weiterbildung:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_confirm_time_model', 'email'::channel, 'de', 'Freistellung und Arbeitszeitmodell', 'Hallo {{firstName}}, bitte bestätigen Sie kurz das Arbeitszeitmodell und die Freistellung für die Weiterbildung:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_employer_setup', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, für den Förderantrag brauchen wir einige Angaben zu Ihrem Unternehmen. Der Assistent führt Sie in wenigen Schritten durch die Felder:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_employer_setup', 'email'::channel, 'de', 'Angaben Ihres Unternehmens für den Förderantrag', 'Hallo {{firstName}}, für den Förderantrag brauchen wir einige Angaben zu Ihrem Unternehmen. Der Assistent führt Sie in wenigen Schritten durch die Felder:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_appointment_reminder', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, wir erinnern Sie an Ihren Beratungstermin. Falls es Ihnen nicht passt, geben Sie uns bitte kurz Bescheid.'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'task_appointment_reminder', 'email'::channel, 'de', 'Erinnerung an Ihren Beratungstermin', 'Hallo {{firstName}}, wir erinnern Sie an Ihren Beratungstermin. Falls es Ihnen nicht passt, geben Sie uns bitte kurz Bescheid.

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'appointment_reminder_24h', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, Ihr Beratungstermin findet morgen statt. Falls Sie verhindert sind, geben Sie uns bitte kurz Bescheid.'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'appointment_reminder_24h', 'email'::channel, 'de', 'Ihr Beratungstermin morgen', 'Hallo {{firstName}}, Ihr Beratungstermin findet morgen statt. Falls Sie verhindert sind, geben Sie uns bitte kurz Bescheid.

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'appointment_reminder_2h', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, Ihr Beratungstermin steht in Kürze an. Wir freuen uns auf das Gespräch.'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'appointment_reminder_2h', 'email'::channel, 'de', 'Ihr Beratungstermin in Kürze', 'Hallo {{firstName}}, Ihr Beratungstermin steht in Kürze an. Wir freuen uns auf das Gespräch.

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'test_reminder_24h', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, Ihr Eignungstest wartet noch auf Sie. Er dauert rund 30 Minuten:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'test_reminder_24h', 'email'::channel, 'de', 'Erinnerung: Ihr Eignungstest', 'Hallo {{firstName}}, Ihr Eignungstest wartet noch auf Sie. Er dauert rund 30 Minuten:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'test_reminder_48h', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, Ihr Eignungstest ist weiterhin offen. Bitte holen Sie ihn in den nächsten Tagen nach, damit Ihr Antrag weiterlaufen kann:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'test_reminder_48h', 'email'::channel, 'de', 'Letzte Erinnerung: Ihr Eignungstest', 'Hallo {{firstName}}, Ihr Eignungstest ist weiterhin offen. Bitte holen Sie ihn in den nächsten Tagen nach, damit Ihr Antrag weiterlaufen kann:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'signature_reminder_24h', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, ein Dokument wartet noch auf Ihre Unterschrift: {{title}}. Sie können es hier unterschreiben:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'signature_reminder_24h', 'email'::channel, 'de', 'Erinnerung: Dokument zur Unterschrift', 'Hallo {{firstName}}, ein Dokument wartet noch auf Ihre Unterschrift: {{title}}. Sie können es hier unterschreiben:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'signature_reminder_72h', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, ohne Ihre Unterschrift können wir den Antrag nicht einreichen: {{title}}. Sie können das Dokument hier unterschreiben:

{{link}}'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'signature_reminder_72h', 'email'::channel, 'de', 'Letzte Erinnerung: Dokument zur Unterschrift', 'Hallo {{firstName}}, ohne Ihre Unterschrift können wir den Antrag nicht einreichen: {{title}}. Sie können das Dokument hier unterschreiben:

{{link}}

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'reminder_generic', 'whatsapp'::channel, 'de', null, 'Hallo {{firstName}}, ein Schritt in Ihrem Förderantrag ist noch offen: {{title}}. Bitte melden Sie sich kurz bei uns.'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
--> statement-breakpoint
insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, 'reminder_generic', 'email'::channel, 'de', 'Erinnerung: offener Schritt in Ihrem Antrag', 'Hallo {{firstName}}, ein Schritt in Ihrem Förderantrag ist noch offen: {{title}}. Bitte melden Sie sich kurz bei uns.

Viele Grüße
Ihr Beratungsteam'
from tenants t
on conflict (tenant_id, key, channel) do nothing;
