import type { routingRules } from "@/db/schema";

// The task-routing matrix from the concept, as data. A tenant without these
// rows looks healthy but never creates a task or sends a message, so both the
// demo seed and the production bootstrap write the same set.

type RoutingRuleInsert = typeof routingRules.$inferInsert;

export function buildDefaultRoutingRules(
  tenantId: string,
): readonly RoutingRuleInsert[] {
  return [
    {
      tenantId,
      name: "Falsche Telefonnummer → Teilnehmer per E-Mail",
      triggerEntity: "participant" as const,
      triggerStatus: "wrong_number",
      taskType: "request_correct_contact",
      titleTemplate: "Korrekte Kontaktdaten angeben",
      ownerKind: "participant" as const,
      channel: "email" as const,
      dueHours: 72,
      escalationHours: 120,
    },
    {
      tenantId,
      name: "Nicht erreichbar → interne Anruf-Aufgabe",
      triggerEntity: "participant" as const,
      triggerStatus: "not_reachable",
      taskType: "retry_call",
      titleTemplate: "Lead erneut anrufen",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24,
    },
    {
      tenantId,
      name: "Nicht erreichbar → Teilnehmer per WhatsApp/E-Mail",
      triggerEntity: "participant" as const,
      triggerStatus: "not_reachable",
      taskType: "confirm_reachability",
      titleTemplate: "Rückmeldung zur Erreichbarkeit geben",
      ownerKind: "participant" as const,
      channel: "whatsapp" as const,
      dueHours: 48,
    },
    {
      tenantId,
      name: "Termin geplant → Erinnerungen",
      triggerEntity: "appointment" as const,
      triggerStatus: "scheduled",
      taskType: "appointment_reminder",
      titleTemplate: "Terminerinnerung",
      ownerKind: "participant" as const,
      channel: "whatsapp" as const,
      reminderPlan: [
        { beforeHours: 24, channel: "whatsapp", templateKey: "appointment_reminder_24h" },
        { beforeHours: 2, channel: "whatsapp", templateKey: "appointment_reminder_2h" },
        { beforeHours: 1, channel: "internal", templateKey: "reminder_call" },
      ],
    },
    {
      tenantId,
      name: "Eignungstest offen → Teilnehmer-Link",
      triggerEntity: "aptitude_test" as const,
      triggerStatus: "invited",
      taskType: "start_aptitude_test",
      titleTemplate: "Eignungstest starten",
      ownerKind: "participant" as const,
      channel: "magic_link" as const,
      dueHours: 48,
      reminderPlan: [
        { afterHours: 24, channel: "whatsapp", templateKey: "test_reminder_24h" },
        { afterHours: 48, channel: "email", templateKey: "test_reminder_48h" },
      ],
      escalationHours: 72,
    },
    {
      tenantId,
      name: "Betriebsnummer fehlt → Arbeitgeber-Link",
      triggerEntity: "employer" as const,
      triggerStatus: "betriebsnummer_missing",
      taskType: "provide_betriebsnummer",
      titleTemplate: "Betriebsnummer angeben",
      ownerKind: "employer" as const,
      channel: "magic_link" as const,
      dueHours: 48,
      escalationHours: 120,
    },
    {
      tenantId,
      name: "AG-S-Status unklar → Arbeitgeber-Link",
      triggerEntity: "employer" as const,
      triggerStatus: "ags_unclear",
      taskType: "confirm_ags_status",
      titleTemplate: "Status beim Arbeitgeberservice bestätigen",
      ownerKind: "employer" as const,
      channel: "magic_link" as const,
      dueHours: 48,
      escalationHours: 120,
    },
    {
      tenantId,
      name: "20h/Woche unbestätigt → Arbeitgeber-Link",
      triggerEntity: "participant" as const,
      triggerStatus: "availability_probably_employer_pending",
      taskType: "confirm_time_model",
      titleTemplate: "Zeitmodell 20h/Woche bestätigen",
      ownerKind: "employer" as const,
      channel: "magic_link" as const,
      dueHours: 72,
      escalationHours: 120,
    },
    {
      tenantId,
      name: "Verfügbarkeit bestätigt → nächste Schritte planen",
      triggerEntity: "participant" as const,
      triggerStatus: "availability_yes",
      taskType: "schedule_next_step",
      titleTemplate: "Nächste Schritte planen (Verfügbarkeit bestätigt)",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 48,
    },
    {
      tenantId,
      name: "Verfügbarkeit teilweise → Beratung klären",
      triggerEntity: "participant" as const,
      triggerStatus: "availability_partial",
      taskType: "clarify_availability",
      titleTemplate: "Verfügbarkeit und Freigabe klären",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 48,
    },
    {
      tenantId,
      name: "Verfügbarkeit unklar → Beratung klären",
      triggerEntity: "participant" as const,
      triggerStatus: "availability_unclear",
      taskType: "clarify_availability",
      titleTemplate: "Verfügbarkeit und Freigabe klären",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 48,
    },
    {
      tenantId,
      name: "Verfügbarkeit nicht möglich → Beratungsgespräch",
      triggerEntity: "participant" as const,
      triggerStatus: "availability_not_possible",
      taskType: "consult_alternatives",
      titleTemplate: "Alternativen besprechen (20h/Woche nicht möglich)",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 72,
    },
    {
      tenantId,
      name: "Dokumentdaten fehlen → zuständige Person",
      triggerEntity: "document" as const,
      triggerStatus: "data_missing",
      taskType: "complete_document_data",
      titleTemplate: "Fehlende Dokumentdaten ergänzen",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 48,
    },
    // Two signature rules — the requestSignature action puts only the actual
    // signer into the transition context, so exactly one of them matches.
    {
      tenantId,
      name: "Signatur fehlt → Unterzeichner-Link (Teilnehmer)",
      triggerEntity: "signature" as const,
      triggerStatus: "pending",
      taskType: "sign_document",
      titleTemplate: "Dokument unterschreiben",
      ownerKind: "participant" as const,
      channel: "magic_link" as const,
      dueHours: 72,
      reminderPlan: [
        { afterHours: 24, channel: "whatsapp", templateKey: "signature_reminder_24h" },
        { afterHours: 72, channel: "email", templateKey: "signature_reminder_72h" },
      ],
      escalationHours: 96,
    },
    {
      tenantId,
      name: "Signatur fehlt → Unterzeichner-Link (Arbeitgeber)",
      triggerEntity: "signature" as const,
      triggerStatus: "pending",
      taskType: "sign_document",
      titleTemplate: "Dokument unterschreiben",
      ownerKind: "employer" as const,
      channel: "magic_link" as const,
      dueHours: 72,
      reminderPlan: [
        { afterHours: 24, channel: "email", templateKey: "signature_reminder_24h" },
        { afterHours: 72, channel: "email", templateKey: "signature_reminder_72h" },
      ],
      escalationHours: 96,
    },
    {
      tenantId,
      name: "Kontaktdaten aktualisiert → erneut anrufen",
      triggerEntity: "participant" as const,
      triggerStatus: "contact_updated",
      taskType: "retry_call",
      titleTemplate: "Lead erneut anrufen (Kontaktdaten aktualisiert)",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24,
    },
    {
      tenantId,
      name: "Termin No-Show → nachfassen + neuen Termin anbieten",
      triggerEntity: "appointment" as const,
      triggerStatus: "no_show",
      taskType: "reschedule_after_no_show",
      titleTemplate: "Neuen Termin vereinbaren",
      ownerKind: "participant" as const,
      channel: "whatsapp" as const,
      dueHours: 48,
      escalationHours: 96,
    },
    {
      tenantId,
      name: "Termin No-Show → interne Nachverfolgung",
      triggerEntity: "appointment" as const,
      triggerStatus: "no_show",
      taskType: "follow_up_no_show",
      titleTemplate: "No-Show nachfassen (Anruf)",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24,
    },
    {
      tenantId,
      name: "Eignungstest bestanden → Dokumente vorbereiten",
      triggerEntity: "aptitude_test" as const,
      triggerStatus: "passed",
      taskType: "prepare_documents",
      titleTemplate: "Antragsunterlagen vorbereiten",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 48,
    },
    {
      tenantId,
      name: "Eignungstest nicht bestanden → Beratung",
      triggerEntity: "aptitude_test" as const,
      triggerStatus: "failed",
      taskType: "consult_alternatives",
      titleTemplate: "Beratungsgespräch: Alternativen empfehlen",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 48,
    },
    {
      tenantId,
      name: "Eignungstest No-Show → neuen Termin anbieten",
      triggerEntity: "aptitude_test" as const,
      triggerStatus: "no_show",
      taskType: "reschedule_after_no_show",
      titleTemplate: "Neuen Testtermin vereinbaren",
      ownerKind: "participant" as const,
      channel: "whatsapp" as const,
      dueHours: 48,
      escalationHours: 96,
    },
    {
      tenantId,
      name: "Antragspaket bereit → Verwaltung",
      triggerEntity: "application" as const,
      triggerStatus: "complete",
      taskType: "review_application_package",
      titleTemplate: "Antragspaket prüfen und freigeben",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24,
    },
    {
      tenantId,
      name: "Einreichung offen → Arbeitgeber",
      triggerEntity: "application" as const,
      triggerStatus: "sent_to_employer",
      taskType: "confirm_submission",
      titleTemplate: "Einreichung beim Arbeitgeberservice bestätigen",
      ownerKind: "employer" as const,
      channel: "magic_link" as const,
      dueHours: 96,
      escalationHours: 168,
    },
    {
      tenantId,
      name: "Eingereicht → Beratung verfolgt Rückmeldung",
      triggerEntity: "application" as const,
      triggerStatus: "submitted",
      taskType: "track_ba_response",
      titleTemplate: "Rückmeldung der Agentur für Arbeit verfolgen",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24 * 10,
      escalationHours: 24 * 21,
    },
    {
      tenantId,
      name: "Antwort ausstehend → Verwaltung Follow-up",
      triggerEntity: "application" as const,
      triggerStatus: "response_pending",
      taskType: "follow_up_ba",
      titleTemplate: "Bei der Agentur für Arbeit nachfassen",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24 * 7,
      escalationHours: 24 * 14,
    },
    {
      tenantId,
      name: "Korrektur erforderlich → Beratung",
      triggerEntity: "application" as const,
      triggerStatus: "correction_required",
      taskType: "correct_application",
      titleTemplate: "Antrag korrigieren und erneut einreichen",
      ownerKind: "internal_user" as const,
      channel: "internal" as const,
      dueHours: 24 * 5,
    },
  ];
}
