/**
 * Emits the data migration that back-fills `message_templates` from the catalog
 * for every existing tenant. Regenerate after editing the catalog:
 *
 *   node --import tsx scripts/generate-template-migration.ts > drizzle/00XX_...sql
 */
import { buildTemplateRows } from "@/modules/messaging/catalog";

const quote = (value: string | null): string =>
  value === null ? "null" : `'${value.replace(/'/g, "''")}'`;

const statements = buildTemplateRows().map(
  (row) => `insert into message_templates (tenant_id, key, channel, locale, subject, body)
select t.id, ${quote(row.key)}, ${quote(row.channel)}::channel, 'de', ${quote(row.subject)}, ${quote(row.body)}
from tenants t
on conflict (tenant_id, key, channel) do nothing;`,
);

process.stdout.write(
  `-- Back-fills the message template catalog for every tenant.
-- Rendering now throws when a (key, channel) has no active row, so these rows
-- are required for any outbound message to leave the system.
-- Generated by scripts/generate-template-migration.ts — do not edit by hand.

${statements.join("\n--> statement-breakpoint\n")}
`,
);
